spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lawingdatabase.com5bfft1iab.ap-northeast-2.rds.amazonaws.com:3306/lawingdatabase?setTimezone=Asia/Seoul
    username: chaen
    password: codms7020!

  sql:
    init:
      mode: always
      data-locations: classpath:/query/server/schema-server.sql
      platform: mysql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true