spring:
  application:
    name: lawing
  profiles:
    include:
      - jwt
      - codef
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  webflux:
    max-buffer-size: 512KB

springdoc:
  swagger-ui:
    path: /lawing/swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
