name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name : Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0.35'
          mysql database: 'lawingdatabase'
          mysql root password: ${{ secrets.DATABASE_PASSWORD }}
          mysql user: 'ec2-user'
          mysql password: ${{ secrets.DATABASE_PASSWORD }}

      - uses: actions/checkout@v3

      #1-1. Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 1-2. Spring Boot Applications Build
      - name: Build with Gradle
        run: ./gradlew build test

      # 1-3. 빌드 결과 확인
      - name: Verify build
        run: ls -l build/libs

      # 1-4. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 1-5. Docker 이미지 빌드
      - name: docker image build
        run: docker build -t chaeniiiii/lawing:latest --platform linux/amd64 .

      # 1-6. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push chaeniiiii/lawing:latest

      # 1-7. Docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port : 22
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull chaeniiiii/lawing
            sudo docker pull chaeniiiii/lawing-nginx
            docker-compose up -d
            sudo docker run -d -p 8080:8080 chaeniiiii/lawing
            docker image prune -f
